# Generated by Django 4.1 on 2025-09-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='year_experience',
            new_name='years_experience',
        ),
    ]
